[toolchain]
channel = "stable"
# channel = "stable-x86_64-unknown-linux-gnu"
# channel = "stable-aarch64-apple-darwin"
components = [ "rustc", "rust-std", "cargo", "rustfmt", "clippy", "rust-src", "rust-docs", "rustc-dev" ]
targets = [ "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "wasm32-unknown-unknown" ]
profile = "complete"
