[toolchain]
channel = "stable"
# channel = "stable-x86_64-unknown-linux-gnu"
# channel = "stable-aarch64-apple-darwin"
components = [ "rustc", "rust-std", "cargo", "rustfmt", "clippy", "rust-src", "rust-docs", "rustc-dev" ]
# linux、windows、macos_arm64、wasm32
targets = [ "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "aarch64-apple-darwin", "wasm32-unknown-unknown" ]
profile = "complete"
